### ISSUE TITLE
EZ-USB fx2lpにem8rl1のfirmwareを書き込んだ場合の挙動について

### ISSUE THREAD

**Issue by hoborakuten** [beijingduckx/em8rl1#1]
初めまして、
非常に興味深いプログラムを提供していただき感謝しております。

題目の件を確認させていただきたいのですが、
現在、EZ-USB fx2lpはWindows11デバイスマネジャーにて認識がされております。
(ユニバーサルシリアルバスコントローラー　cypress ez usb fx2lp no eeprom device)
EZ-USB fx2lpに添付されていたサンプルのファームウェア（bulkloop.hex）をRAMに書き込むと、
正常な動きをしているようです。
（デバイスマネジャーの名前がCypress FX2LP Sample Deviceに変わります。）

コンパイラした「em8rl1.ihx（hex?）」を書き込みますと変化がないように思います。
「Cypress USB　CONTROL  CENTER」にて書き込んでいますが、一番下に「Programming succeeded」と表示されます。
しかし、Windows11にて「em8RL1.exe」を実行しますと「EZ-USB not connected」と表示されます。

動作的には正しいのかご助言お願いいたします。
お忙しいところ恐縮ですがよろしくお願い致します。

**Comment by beijingduckx** [comment]
興味を持っていただき、ありがとうございます

em8rl1を使用する際、EZ-USBはCypress製のドライバではなく、WinUSBドライバで認識されるように
設定します。

ご参考までに、以下に手順を記します。

**注意: 以下の作業後は、Cypress製のツールが EZ-USBを認識しなくなります** 
(以下の作業した時とは別のUSBポートに接続すると認識すると思います)  

1. [Zadigをダウンロードします](https://zadig.akeo.ie/)
2. Zadigを起動し、Optionsの`List All Devices`をチェックします
3. おそらく`Unknown Device #1` か、`Cypress...` のデバイスを選択します
4. USB IDが、04B4, 8613 になっていることを確認します (**必ず確認してください**)
5. Driverが WinUSBになっていることを確認して、`Install Driver`を押します
6. 時間がかかるかもしれませんが、終了まで待ちます

この後、em8rl1.exe を実行すれば、em8rl1.exe の中でファームウェアをEZ-USBにダウンロードし、
USBデバイスとして動作します。

**Comment by hoborakuten** [comment]
beijingduckx様
迅速かつ詳細な助言をいただきありがとうございます。
これから試してみようと思いますが、取り急ぎ感謝させていただきます。
誠にありがとうございます！

**Comment by hoborakuten** [comment]
beijingduckx様

先日は、ご助言いただきありがとうございました。
あれから配線等作成しまして動作確認できました。
NEC系などデータレコーダエミュ「Raspberry Pi用ピーガーMODEM」は手元にありますが、
X1は変調方式が違うとのことで困っておりました。

動作確認のご報告と、もう一度感謝させていただきます。
ありがとうございました。

**Comment by beijingduckx** [comment]
ご報告ありがとうございました!
